### PR TITLE
Basic tests for TaskQueue features

### PR DESCRIPTION
**Pull request by OdeToCode**

### CODE REVIEW

**Comment by AshleyGrant** [comment]
I think this might be a better way to do the second test, though please let me know if my test tests things differently from what you were testing.

``` javascript
  it("will execute tasks in the correct order", done => {
    let task1HasRun = false;
    let task1 = () => {
      task1HasRun = true;
    };
    let task2 = () => {
      if(task1HasRun === true){
        done();
      }
    };

    let queue = new TaskQueue();
    queue.queueTask(task1);
    queue.queueTask(task2);
  });
```

Thoughts?

**Comment by OdeToCode** [comment]
Sounds good - I wasn't sure if this behavior was guaranteed, but it is good to know the ordering is enforced.

**Comment by AshleyGrant** [comment]
Could you update your commit messages to follow the preferred format for the project, please. It's located here: https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#commit

In your case, `test(task-queue): basic tests for task-queue features` would likely suffice.

Thanks, it's great to work with you!

**Comment by OdeToCode** [comment]
Updated correctly, I believe. I won't let that happen again. :)

**Comment by EisenbergEffect** [comment]
No problem :) Great to see you here Scott. Thanks for the contribution. I'll take a look at it shortly.

**Comment by kyeotic** [comment]
@AshleyGrant The way your test is written, if the tasks _dont_ execute in the right order, the test will fail only when it times out. I think it would be better to use

``` lang-javascript
let task2 = () => {
    expect(tast1HasRun).toEqual(true);
    done();
};
```

so that the test will fail immediately if false. Additionally, this will provide a better error for the reporter, instead of the normal test timeout message.

**Comment by AshleyGrant** [comment]
Good point. I missed that.

**Comment by kyeotic** [comment]
@OdeToCode Just to notify you of the above comments, so that you can update the tests.

**Comment by OdeToCode** [comment]
Thanks, @tyrsius, squished it in.

**Comment by EisenbergEffect** [comment]
@OdeToCode Thanks for getting the ball rolling with some tests on this!

**Pull request merged**
